# Generated by Django 4.1.5 on 2023-01-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='creted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='creted_by',
            new_name='created_by',
        ),
    ]
