# Generated by Django 4.1.5 on 2023-01-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_rename_creted_at_lead_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='covert_to_client',
            field=models.BooleanField(default=False),
        ),
    ]
