# Generated by Django 4.1.5 on 2023-01-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_lead_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('name',)},
        ),
    ]
